using System;

namespace BaseLib.Config;

/// <summary>
/// <para>Defines the allowed characters and max length for the LineEdit generated by a string property.<br />
/// You can specify a <see cref="T:BaseLib.Config.TextInputPreset" /> or a custom Regex string for the allowed characters. By default,
/// any string is allowed, at any length.</para>
/// If a placeholder LocString exists (YOURMOD-PROPERTY_NAME.placeholder), it will be used; if you don't want a
/// placeholder, simply skip creating such a string.
/// </summary>
[AttributeUsage(AttributeTargets.Property)]
public class ConfigTextInputAttribute : Attribute
{
	public string AllowedCharactersRegex { get; }

	public int MaxLength { get; set; }

	public ConfigTextInputAttribute()
		: this(TextInputPreset.Anything)
	{
	}

	public ConfigTextInputAttribute(TextInputPreset preset)
	{
		AllowedCharactersRegex = preset switch
		{
			TextInputPreset.Alphanumeric => "[a-zA-Z0-9]+", 
			TextInputPreset.AlphanumericWithSpaces => "[a-zA-Z0-9 ]+", 
			TextInputPreset.SafeDisplayName => "[\\p{L}\\d_\\- ]+", 
			_ => ".*", 
		};
	}

	public ConfigTextInputAttribute(string customRegex)
	{
		AllowedCharactersRegex = customRegex;
	}
}
